### ISSUE TITLE
Getting queueData is not a validation rules group error

### ISSUE THREAD

**Issue by snehal90** [daycry/queues#2]
Hello,
I have installed 2.0.0 version of this plugin. But after publish I am getting an error saving "queueData is not a validation rules group.".
Code I have added is as below:

> use Daycry\Queues\Job;
> $job = new Job();
> $job->classes(\App\Controllers\QueueTest::class, 'index')->enqueue('default');

Screenshot of error when I try to execute it:
![image](https://github.com/daycry/queues/assets/25900347/18facb67-995a-4307-be92-8698cf881f02)

Though I have checked it in plugin and I have found the validation group in `src/Config/Registrar.php` file
![image](https://github.com/daycry/queues/assets/25900347/356fcc78-ee03-4776-914f-6206a30859d7)

Could someone please help me with this as soon as possible?

Thanks & regards,
Snehal

**Comment by snehal90** [comment]
I have also found one issue with SyncQueue class. It has only enqueue() function. But to run queue worker we need watch() function as well. 
While running queues::worker command its throwing error as 
![image](https://github.com/daycry/queues/assets/25900347/c80311c2-b1b2-4a21-afc5-8f524c291a0b)

Could someone guide me to resolve these issues?
Thanks in advance.

**Comment by daycry** [comment]
Hi!

I fixed this error in new versions.

**Comment by snehal90** [comment]
Hello @daycry ,
I have updated the version on local and took latest build of package but issue is still there.
Could you please guide me to resolve it?

**Comment by daycry** [comment]
Let me see, because I removed the registrar class for compatibility with
PHP 8.2.

Sorry.

**Comment by daycry** [comment]
Sync queue execute directly the job.

When you use Sync queue return the result of the job when you use enqueue
method.

**Comment by rrozaq** [comment]
I'm experiencing an issue when trying to enqueue a job using `daycry/queue`.  
After upgrading to the latest version, I get a validation error related to `"queueData"`.

**Code Sample**  
```php
$job = new Job();
$job->classes(\App\Jobs\MyJob::class, 'handle', [ 
    'constructor' => $data
])->enqueue('default');
```

And the error occurs when executing
my logs:

```
INFO - 2025-03-13 15:24:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-03-13 15:24:09 --> "queueData" is not a validation rules group.
in SYSTEMPATH\Validation\Validation.php on line 684.
 1 SYSTEMPATH\Validation\Validation.php(684): CodeIgniter\Validation\Exceptions\ValidationException::forGroupNotFound('queueData')
 2 SYSTEMPATH\Validation\Validation.php(132): CodeIgniter\Validation\Validation->loadRuleGroup('queueData')
 3 VENDORPATH\daycry\queues\src\Libraries\Utils.php(30): CodeIgniter\Validation\Validation->run([...], 'queueData')
 4 VENDORPATH\daycry\queues\src\Traits\EnqueuableTrait.php(47): Daycry\Queues\Libraries\Utils::checkDataQueue([...], 'queueData')
 5 APPPATH\Controllers\PromoCardController.php(5810): Daycry\Queues\Job->enqueue('default')
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\PromoCardController->export()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PromoCardController))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
```

thankyou

**Comment by daycry** [comment]
I can't reproduce the error, I'm using version v2.0.15 and it works correctly.

**Comment by daycry** [comment]
![Image](https://github.com/user-attachments/assets/386a6cf3-71a9-44c0-960a-7bfb84a97dcc)
